#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleDSLV.Resource", IsApplication=true)]

namespace SampleDSLV
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DragSortListview.Resource.Attribute.click_remove_id = global::SampleDSLV.Resource.Attribute.click_remove_id;
			global::DragSortListview.Resource.Attribute.collapsed_height = global::SampleDSLV.Resource.Attribute.collapsed_height;
			global::DragSortListview.Resource.Attribute.drag_enabled = global::SampleDSLV.Resource.Attribute.drag_enabled;
			global::DragSortListview.Resource.Attribute.drag_handle_id = global::SampleDSLV.Resource.Attribute.drag_handle_id;
			global::DragSortListview.Resource.Attribute.drag_scroll_start = global::SampleDSLV.Resource.Attribute.drag_scroll_start;
			global::DragSortListview.Resource.Attribute.drag_start_mode = global::SampleDSLV.Resource.Attribute.drag_start_mode;
			global::DragSortListview.Resource.Attribute.drop_animation_duration = global::SampleDSLV.Resource.Attribute.drop_animation_duration;
			global::DragSortListview.Resource.Attribute.fling_handle_id = global::SampleDSLV.Resource.Attribute.fling_handle_id;
			global::DragSortListview.Resource.Attribute.float_alpha = global::SampleDSLV.Resource.Attribute.float_alpha;
			global::DragSortListview.Resource.Attribute.float_background_color = global::SampleDSLV.Resource.Attribute.float_background_color;
			global::DragSortListview.Resource.Attribute.max_drag_scroll_speed = global::SampleDSLV.Resource.Attribute.max_drag_scroll_speed;
			global::DragSortListview.Resource.Attribute.remove_animation_duration = global::SampleDSLV.Resource.Attribute.remove_animation_duration;
			global::DragSortListview.Resource.Attribute.remove_enabled = global::SampleDSLV.Resource.Attribute.remove_enabled;
			global::DragSortListview.Resource.Attribute.remove_mode = global::SampleDSLV.Resource.Attribute.remove_mode;
			global::DragSortListview.Resource.Attribute.slide_shuffle_speed = global::SampleDSLV.Resource.Attribute.slide_shuffle_speed;
			global::DragSortListview.Resource.Attribute.sort_enabled = global::SampleDSLV.Resource.Attribute.sort_enabled;
			global::DragSortListview.Resource.Attribute.track_drag_sort = global::SampleDSLV.Resource.Attribute.track_drag_sort;
			global::DragSortListview.Resource.Attribute.use_default_controller = global::SampleDSLV.Resource.Attribute.use_default_controller;
			global::DragSortListview.Resource.Id.clickRemove = global::SampleDSLV.Resource.Id.clickRemove;
			global::DragSortListview.Resource.Id.flingRemove = global::SampleDSLV.Resource.Id.flingRemove;
			global::DragSortListview.Resource.Id.onDown = global::SampleDSLV.Resource.Id.onDown;
			global::DragSortListview.Resource.Id.onLongPress = global::SampleDSLV.Resource.Id.onLongPress;
			global::DragSortListview.Resource.Id.onMove = global::SampleDSLV.Resource.Id.onMove;
			global::DragSortListview.Resource.String.ApplicationName = global::SampleDSLV.Resource.String.ApplicationName;
			global::DragSortListview.Resource.String.Hello = global::SampleDSLV.Resource.String.Hello;
			global::DragSortListview.Resource.Styleable.DragSortListView = global::SampleDSLV.Resource.Styleable.DragSortListView;
			global::DragSortListview.Resource.Styleable.DragSortListView_click_remove_id = global::SampleDSLV.Resource.Styleable.DragSortListView_click_remove_id;
			global::DragSortListview.Resource.Styleable.DragSortListView_collapsed_height = global::SampleDSLV.Resource.Styleable.DragSortListView_collapsed_height;
			global::DragSortListview.Resource.Styleable.DragSortListView_drag_enabled = global::SampleDSLV.Resource.Styleable.DragSortListView_drag_enabled;
			global::DragSortListview.Resource.Styleable.DragSortListView_drag_handle_id = global::SampleDSLV.Resource.Styleable.DragSortListView_drag_handle_id;
			global::DragSortListview.Resource.Styleable.DragSortListView_drag_scroll_start = global::SampleDSLV.Resource.Styleable.DragSortListView_drag_scroll_start;
			global::DragSortListview.Resource.Styleable.DragSortListView_drag_start_mode = global::SampleDSLV.Resource.Styleable.DragSortListView_drag_start_mode;
			global::DragSortListview.Resource.Styleable.DragSortListView_drop_animation_duration = global::SampleDSLV.Resource.Styleable.DragSortListView_drop_animation_duration;
			global::DragSortListview.Resource.Styleable.DragSortListView_fling_handle_id = global::SampleDSLV.Resource.Styleable.DragSortListView_fling_handle_id;
			global::DragSortListview.Resource.Styleable.DragSortListView_float_alpha = global::SampleDSLV.Resource.Styleable.DragSortListView_float_alpha;
			global::DragSortListview.Resource.Styleable.DragSortListView_float_background_color = global::SampleDSLV.Resource.Styleable.DragSortListView_float_background_color;
			global::DragSortListview.Resource.Styleable.DragSortListView_max_drag_scroll_speed = global::SampleDSLV.Resource.Styleable.DragSortListView_max_drag_scroll_speed;
			global::DragSortListview.Resource.Styleable.DragSortListView_remove_animation_duration = global::SampleDSLV.Resource.Styleable.DragSortListView_remove_animation_duration;
			global::DragSortListview.Resource.Styleable.DragSortListView_remove_enabled = global::SampleDSLV.Resource.Styleable.DragSortListView_remove_enabled;
			global::DragSortListview.Resource.Styleable.DragSortListView_remove_mode = global::SampleDSLV.Resource.Styleable.DragSortListView_remove_mode;
			global::DragSortListview.Resource.Styleable.DragSortListView_slide_shuffle_speed = global::SampleDSLV.Resource.Styleable.DragSortListView_slide_shuffle_speed;
			global::DragSortListview.Resource.Styleable.DragSortListView_sort_enabled = global::SampleDSLV.Resource.Styleable.DragSortListView_sort_enabled;
			global::DragSortListview.Resource.Styleable.DragSortListView_track_drag_sort = global::SampleDSLV.Resource.Styleable.DragSortListView_track_drag_sort;
			global::DragSortListview.Resource.Styleable.DragSortListView_use_default_controller = global::SampleDSLV.Resource.Styleable.DragSortListView_use_default_controller;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080001
			public const int activity_descs = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int activity_titles = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int countries = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int drag_init_mode_labels = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int enables_labels = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int jazz_artist_albums = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int jazz_artist_names = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int remove_mode_labels = 2131230722;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int click_remove_id = 2130771984;
			
			// aapt resource value: 0x7f010000
			public const int collapsed_height = 2130771968;
			
			// aapt resource value: 0x7f01000a
			public const int drag_enabled = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int drag_handle_id = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int drag_scroll_start = 2130771969;
			
			// aapt resource value: 0x7f01000d
			public const int drag_start_mode = 2130771981;
			
			// aapt resource value: 0x7f010009
			public const int drop_animation_duration = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int fling_handle_id = 2130771983;
			
			// aapt resource value: 0x7f010006
			public const int float_alpha = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int float_background_color = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int max_drag_scroll_speed = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int remove_animation_duration = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int remove_enabled = 2130771980;
			
			// aapt resource value: 0x7f010004
			public const int remove_mode = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int slide_shuffle_speed = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public const int sort_enabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int track_drag_sort = 2130771973;
			
			// aapt resource value: 0x7f010011
			public const int use_default_controller = 2130771985;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060006
			public const int bg_handle_pressed = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int black = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int blue = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int darkblue = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int grayend = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int graystart = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int red = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int item_height = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int section_div_height = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_handle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_handle_section1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_handle_section1_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_handle_section2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_handle_section2_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int delete_x = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int drag = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dslv_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int section_div = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000c
			public const int activity_desc = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int activity_title = 2130968587;
			
			// aapt resource value: 0x7f040013
			public const int add_footer = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int add_header = 2130968594;
			
			// aapt resource value: 0x7f04000a
			public const int artist_albums_textview = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int artist_name_textview = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int bg_handle = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int clickRemove = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int click_remove = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int drag_handle = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int flingRemove = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int onDown = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int onLongPress = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int onMove = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int section_div = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int select_drag_init_mode = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int select_enables = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int select_remove_mode = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int test_bed = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int text = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bg_handle_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int checkable_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int cursor_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dslv_fragment_main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int header_footer = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hetero_main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int jazz_artist_list_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int launcher = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int launcher_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int list_item_bg_handle = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int list_item_checkable = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int list_item_click_remove = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int list_item_handle_left = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int list_item_handle_right = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int list_item_no_handle = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int list_item_radio = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int section_div = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int sections_main = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int test_bed_main = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int warp_main = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int mode_menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int add_footer = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int add_header = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int cancel = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int ok = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int select_drag_init_mode = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int select_enables = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int select_remove_mode = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] DragSortListView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 16
			public const int DragSortListView_click_remove_id = 16;
			
			// aapt resource value: 0
			public const int DragSortListView_collapsed_height = 0;
			
			// aapt resource value: 10
			public const int DragSortListView_drag_enabled = 10;
			
			// aapt resource value: 14
			public const int DragSortListView_drag_handle_id = 14;
			
			// aapt resource value: 1
			public const int DragSortListView_drag_scroll_start = 1;
			
			// aapt resource value: 13
			public const int DragSortListView_drag_start_mode = 13;
			
			// aapt resource value: 9
			public const int DragSortListView_drop_animation_duration = 9;
			
			// aapt resource value: 15
			public const int DragSortListView_fling_handle_id = 15;
			
			// aapt resource value: 6
			public const int DragSortListView_float_alpha = 6;
			
			// aapt resource value: 3
			public const int DragSortListView_float_background_color = 3;
			
			// aapt resource value: 2
			public const int DragSortListView_max_drag_scroll_speed = 2;
			
			// aapt resource value: 8
			public const int DragSortListView_remove_animation_duration = 8;
			
			// aapt resource value: 12
			public const int DragSortListView_remove_enabled = 12;
			
			// aapt resource value: 4
			public const int DragSortListView_remove_mode = 4;
			
			// aapt resource value: 7
			public const int DragSortListView_slide_shuffle_speed = 7;
			
			// aapt resource value: 11
			public const int DragSortListView_sort_enabled = 11;
			
			// aapt resource value: 5
			public const int DragSortListView_track_drag_sort = 5;
			
			// aapt resource value: 17
			public const int DragSortListView_use_default_controller = 17;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
